[dependencies]
chrono = '0.4.19'
num-traits = '0.2.14'
serde = '1.0.119'
serde_derive = '1.0.119'

[dependencies.scorus]
git = 'https://github.com/astrojhgu/scorus.git'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'astroalgo'
version = '0.1.0'
