[dependencies]
chrono = '0.4.22'
num-traits = '0.2.15'
serde = '1.0.145'
serde_derive = '1.0.145'

[dependencies.scorus]
path = '../scorus'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'astroalgo'
version = '0.1.0'
