[dependencies]
chrono = '0.4.9'
num-traits = '0.2.8'
serde = '1.0.102'
serde_derive = '1.0.102'

[dependencies.scorus]
git = 'https://github.com/astrojhgu/scorus.git'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'astroalgo'
version = '0.1.0'
