[dependencies]
chrono = '0.4.6'
num-traits = '0.2.6'
serde = '1.0.80'
serde_derive = '1.0.80'

[dependencies.scorus]
path = '../scorus'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
name = 'astroalgo'
version = '0.1.0'
